const ENCRYPTED_FILE_EXTENSION_ENCRYPTED = 'encrypted';
const ENCRYPTED_FILE_EXTENSION_MDENC = 'mdenc';
export const ENCRYPTED_FILE_EXTENSION_ENC = 'enc';

export const ENCRYPTED_FILE_EXTENSION_DEFAULT = ENCRYPTED_FILE_EXTENSION_ENC;


export const ENCRYPTED_FILE_EXTENSIONS = [
	ENCRYPTED_FILE_EXTENSION_ENC,
	ENCRYPTED_FILE_EXTENSION_MDENC,
	ENCRYPTED_FILE_EXTENSION_ENCRYPTED
];